### ISSUE TITLE
ros_control implementation

### ISSUE THREAD

**Issue by philwall3** [ros-industrial-attic/robotiq#120]
Hi,
does anyone already have ros_control implemented for their real robotiq Gripper. I'm trying to do this now and I'm a bit lost on how to do it. 

Thanks!

**Comment by jproberge** [comment]
Hello @philwall3 

I'm aware your message was written months ago, but in the meantime, Robotiq's maintainer of their ros packages has changed. So, do you still have any problem using a Robotiq gripper with ros?

**Comment by philwall3** [comment]
Hi @jproberge  
I've managed to use the ros_control implementation from Carlos J. Rosales (https://github.com/beta-robots/robotiq).
This is my project: https://github.com/philwall3/UR5-with-Robotiq-Gripper-and-Kinect

**Comment by Danfoa** [comment]
Hello @philwall3, thank you very much for the link to your project, we are facing the same issue and will be working based on what you did, I have two question:

1. Actually I do not see where do you use any of the [Betha-Robotics repo](https://github.com/beta-robots/robotiq), as far as I notice you are using the [robotiq_modbus_rtu and robotiq_c_model_control](https://github.com/ros-industrial/robotiq/tree/jade-devel/robotiq_modbus_rtu) repos from the ros-industrial/robotiq repository to establish a connection.

2. And secondly would you consider creating a tutorial on the [wiki.ros.org/robotiq/Tutorials](http://wiki.ros.org/robotiq/Tutorials) page?, there is actually one half done that tries to address the instructions for Modbus RTU communication, but it is incomplete, and since you already have the experience, I don't think it will take you too much time to do it (just a suggestion).

**Comment by philwall3** [comment]
1. I'm only using the ros_control implementation from Beta-Robots. It's instantiated here: https://github.com/philwall3/UR5-with-Robotiq-Gripper-and-Kinect/blob/master/myrobot2/myrobot2_driver/launch/myrobot2_bringup_ros_control.launch#L45

2. Since the ros_control implementation is done by @carlosjoserg and I'm just using it, I can't really help with that. Sorry.
