### ISSUE TITLE
English comments

### ISSUE THREAD

**Issue by NikolasE** [ros-industrial-attic/robotiq#90]
The comments are in english and french and I think they should be a) in a single language and b) in english.

**Comment by shaun-edwards** [comment]
@NikolasE, I took a quick look and couldn't find any French comments.  Can you provide a link?  

Do you have a particular concern?  The original developer spoke French, so I assume that is why they are in there.

**Comment by NikolasE** [comment]
https://github.com/ros-industrial/robotiq/blob/jade-devel/robotiq_force_torque_sensor/src/rq_sensor_com.cpp#L440

"Do you have a particular concern?" It's just inconsistent and if the author thought that a comment was needed, then as many users as possible should be able to understand it.

**Comment by shaun-edwards** [comment]
From your original post, I thought there were the same comments in two different languages.  This would certainly be impossible to maintain for non-speakers.  I think converting french only comments to english is reasonable.  I normally wouldn't suggest we override the original author's intent, but since most comments are in english, I expect this was just an oversight.  

This could be done as needed (whenever someone is making changes) or on whole is someone wanted to take the time to google translate.  I'd accept a PR on this.

**Comment by lit-af** [comment]
@shaun-edwards This issue could be closed.

**Comment by gavanderhoorn** [comment]
@shaun-edwards is no longer maintaining this repository. That would be @jproberge.
